Add courses files and .gitignore
MariaFdezJ/learning_js pull request #1
Opened 2019-01-29 02:52 UTC by MariaFdezJ

Purpose of this PR is just to add courses files and .gitignore file. 

- [ ] Code Review
- [ ] Any other feedback?

2019-01-29 04:01 UTC, csuriel requested changes
Noticed that you have different indentation in some files. Consider to add a [`.editorconfig`](https://editorconfig.org/) file in your repo so you have a consistent coding style.

Here is an example based on what I'm using:
```
# http://editorconfig.org
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

2019-01-29 04:01 UTC, csuriel commented on courses/iife/button.html
> +<!-- button.html -->
It is a good idea to add the [<!DOCTYPE>](https://www.w3schools.com/tags/tag_doctype.asp) declaration before your `html` tag.

2019-01-29 04:01 UTC, csuriel commented on courses/iife/button.html
> +</html>
Always add a new line at the end of files. [Here](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file) you can read about it.

Also, in my opinion, having empty lines between every `html` element makes your code easier to read but it could be overkilled if you already have a nice indentation. You may want to have more information in your screen at the same time instead.

2019-01-29 04:01 UTC, csuriel commented on courses/transpiling/ES5/code.js
> +'use strict';
This file is generated from another file. You could excluded from the repo and add the information about how to generate it in the readme file.

2019-02-03 23:22 UTC, MariaFdezJ commented
@csuriel ready for another review!

2019-02-04 12:52 UTC, arieljimenez commented
> Noticed that you have different indentation in some files. Consider to add a [`.editorconfig`](https://editorconfig.org/) file in your repo so you have a consistent coding style.
> 
> Here is an example based on what I'm using:
> 
> ```
> # http://editorconfig.org
> root = true
> 
> [*]
> indent_style = space
> indent_size = 2
> end_of_line = lf
> charset = utf-8
> trim_trailing_whitespace = true
> insert_final_newline = true
> 
> [*.md]
> trim_trailing_whitespace = false
> ```

Also we can use a linter like [Eslint](https://eslint.org/), so with the correct config, the `console` can yell at us if see something _shifty_.

2019-02-06 14:19 UTC, csuriel approved these changes

2019-03-03 01:21 UTC, merged